waypoints:
  - name: rotate
    frame_id: map
    pose:
      position:
        x: .21
        y: 0
        z: 0
      orientation:
        x: 0
        y: 0
        z: 1
        w: 0
  - name: couch
    frame_id: map
    pose:
      position:
        x: -2.90
        y: 0
        z: 0
      orientation:
        x: 0
        y: 0
        z: -.7
        w: .7
  - name: gap
    frame_id: map
    pose:
      position:
        x: -2.9
        y: -3.0
        z: 0
      orientation:
        x: 0
        y: 0
        z: 0
        w: 1
  - name: bybigpc
    frame_id: map
    pose:
      position:
        x: -2.9
        y: -3.0
        z: 0
      orientation:
        x: 0
        y: 0
        z: -0.7
        w: 0.7
  - name: behindcouch
    frame_id: map
    pose:
      position:
        x: 0
        y: -3.0
        z: 0
      orientation:
        x: 0
        y: 0
        z: 0
        w: 1
  - name: bydoor
    frame_id: map
    pose:
      position:
        x: 2.9
        y: -3.3
        z: 0
      orientation:
        x: 0
        y: 0
        z: 0
        w: 1
  - name: bystairs
    frame_id: map
    pose:
      position:
        x: 2.9
        y: -3.9
        z: 0
      orientation:
        x: 0
        y: 0
        z: 0
        w: 1


trajectories:
  - name: go_to_door
    waypoints:
    - rotate
    - couch
    - gap
    - behindcouch
    - bydoor
    - bystairs
  - name: go_to_room2
    waypoints:
    - couch
    - behindcouch
    - bystairs
